name: Extract MuJoCo binary

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Release tag"
        required: true
        type: string
      platform:
        description: "Platform"
        required: true
        type: choice
        options:
          - windows
          - macos
          - linux_arm
          - linux_x86

jobs:
  extract-binary:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        TAG=${{ inputs.tag_name }}

        case ${{ inputs.platform }} in

          windows)
            ARCHIVE_FILE_NAME="mujoco-$TAG-windows-x86_64.zip"
            PATH_IN_ARCHIVE="bin\mujoco.dll"
            FILE_NAME_AFTER_EXTRACT="bin\mujoco.dll"
            FINAL_FILE_NAME="mujoco.dll"
            ;;

          macos)
            ARCHIVE_FILE_NAME="mujoco-$TAG-macos-universal2.dmg"
            PATH_IN_ARCHIVE="mujoco.framework/Versions/A/libmujoco.$TAG.dylib"
            FILE_NAME_AFTER_EXTRACT="libmujoco.$TAG.dylib"
            FINAL_FILE_NAME="mujoco.dylib"
            ;;

          linux_arm)
            ARCHIVE_FILE_NAME="mujoco-$TAG-linux-aarch64.tar.gz"
            PATH_IN_ARCHIVE="mujoco-$TAG/lib/libmujoco.so.$TAG"
            FILE_NAME_AFTER_EXTRACT="libmujoco.so.$TAG"
            FINAL_FILE_NAME="libmujoco_arm.so"
            ;;

          linux_x86)
            ARCHIVE_FILE_NAME="mujoco-$TAG-linux-x86_64.tar.gz"
            PATH_IN_ARCHIVE="mujoco-$TAG/lib/libmujoco.so.$TAG"
            FILE_NAME_AFTER_EXTRACT="libmujoco.so.$TAG"
            FINAL_FILE_NAME="libmujoco_x86.so"
            ;;
        esac

        echo "TAG=\"$TAG\"" >> $GITHUB_ENV
        echo "ARCHIVE_FILE_NAME=\"$ARCHIVE_FILE_NAME\"" >> $GITHUB_ENV
        echo "PATH_IN_ARCHIVE=\"$PATH_IN_ARCHIVE\"" >> $GITHUB_ENV
        echo "FILE_NAME_AFTER_EXTRACT=\"$FILE_NAME_AFTER_EXTRACT\"" >> $GITHUB_ENV
        echo "FINAL_FILE_NAME=\"$FINAL_FILE_NAME\"" >> $GITHUB_ENV

    - name: Install 7z tool
      run: |
        wget https://www.7-zip.org/a/7z2408-linux-x64.tar.xz
        tar -xJf 7z2408-linux-x64.tar.xz
        ls
        stat ./7zz

    - name: Download archive
      uses: valitydev/action-download-file@v1
      with:
        url: https://github.com/google-deepmind/mujoco/releases/download/${{ env.TAG }}/${{ env.ARCHIVE_FILE_NAME }}
        target-path: .

    - name: Extract library binary
      run: |
        ARCHIVE_FILE_NAME=${{ env.ARCHIVE_FILE_NAME }}
        if [[ "$ARCHIVE_FILE_NAME" == *.gz ]]; then
          ./7zz e $ARCHIVE_FILE_NAME
          ARCHIVE_FILE_NAME=${ARCHIVE_FILE_NAME%.*} # remove .gz
        fi

        ./7zz e "$ARCHIVE_FILE_NAME" ${{ env.PATH_IN_ARCHIVE }}
        ls
        mv ${{ env.FILE_NAME_AFTER_EXTRACT }} ${{ env.FINAL_FILE_NAME }}
        stat ${{ env.FINAL_FILE_NAME }}

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
        REPO_FULL_NAME: ${{ github.repository }}
      run: |
        # workaround for gh bug
        # https://github.com/cli/cli/issues/9072#issuecomment-2106065080
        git init -b main
        git remote add origin "https://github.com/$REPO_FULL_NAME"

        gh release upload upm-${{ env.TAG }} ${{ env.FINAL_FILE_NAME }}
