name: Extract MuJoCo binary

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Release tag"
        required: true
        type: string
      platform:
        description: "Platform"
        required: true
        type: choice
        options:
          - windows
          - macos
          - linux_arm
          - linux_x86

jobs:
  extract-binary:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        TAG=${{ inputs.tag_name }}
        echo "TAG=$TAG" >> $GITHUB_ENV

        case ${{ inputs.platform }} in

          windows)
            echo "FINAL_FILE_NAME=mujoco.dll" >> $GITHUB_ENV
            echo "ARCHIVE_FILE_NAME=mujoco-$TAG-windows-x86_64.zip" >> $GITHUB_ENV
            echo "PATH_IN_ARCHIVE=bin\mujoco.dll" >> $GITHUB_ENV
            ;;

          macos)
            echo "FINAL_FILE_NAME=mujoco.dylib" >> $GITHUB_ENV
            echo "ARCHIVE_FILE_NAME=mujoco-$TAG-macos-universal2.dmg" >> $GITHUB_ENV
            echo "PATH_IN_ARCHIVE=mujoco.framework/Versions/A/libmujoco.$TAG.dylib" >> $GITHUB_ENV
            ;;

          linux_arm)
            echo "FINAL_FILE_NAME=libmujoco_arm.so" >> $GITHUB_ENV
            echo "ARCHIVE_FILE_NAME=mujoco-$TAG-linux-aarch64.tar.gz" >> $GITHUB_ENV
            echo "PATH_IN_ARCHIVE=mujoco-$TAG/lib/libmujoco.so.$TAG" >> $GITHUB_ENV
            ;;

          linux_x86)
            echo "FINAL_FILE_NAME=libmujoco_x86.so" >> $GITHUB_ENV
            echo "ARCHIVE_FILE_NAME=mujoco-$TAG-linux-x86_64.tar.gz" >> $GITHUB_ENV
            echo "PATH_IN_ARCHIVE=mujoco-$TAG/lib/libmujoco.so.$TAG" >> $GITHUB_ENV
            ;;
        esac

    - name: Download archive
      uses: valitydev/action-download-file@v1
      with:
        url: https://github.com/google-deepmind/mujoco/releases/download/${{ env.TAG }}/${{ env.ARCHIVE_FILE_NAME }}
        target-path: .

    - name: Install archive tool
      run: |
        sudo apt-get install -y p7zip-full

    - name: Extract library binary
      run: |
        if [[ "${{ inputs.platform }}" == *.gz ]]; then
          7z e ${{ env.ARCHIVE_FILE_NAME }}
        fi
        7z e ${{ env.ARCHIVE_FILE_NAME }} -so "${{ env.PATH_IN_ARCHIVE }}" > ${{ env.FINAL_FILE_NAME }}

    - name: Log folder contents
      run: |
        ls
        stat ${{ env.FINAL_FILE_NAME }}

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
        REPO_FULL_NAME: ${{ github.repository }}
      run: |
        # workaround for gh bug
        # https://github.com/cli/cli/issues/9072#issuecomment-2106065080
        git init -b main
        git remote add origin "https://github.com/$REPO_FULL_NAME"

        gh release upload upm-${{ env.TAG }} ${{ env.FINAL_FILE_NAME }}
