name: Extract MuJoCo binary

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Release tag"
        required: true
        type: string
      platform:
        description: "Platform"
        required: true
        type: choice
        options:
          - windows
          - macos
          - linux_arm
          - linux_x86

jobs:
  extract-binary:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        TAG=${{ inputs.tag_name }}
        echo "TAG=$TAG" >> $GITHUB_ENV

        case ${{ inputs.platform }} in

          windows)
            echo "FINAL_FILE_NAME=mujoco.dll" >> $GITHUB_ENV
            echo "ARCHIVE_FILE_NAME=mujoco-$TAG-windows-x86_64.zip" >> $GITHUB_ENV
            echo "PATH_IN_ARCHIVE=bin\mujoco.dll" >> $GITHUB_ENV
            ;;

          macos)
            echo "FINAL_FILE_NAME=mujoco.dylib" >> $GITHUB_ENV
            echo "ARCHIVE_FILE_NAME=mujoco-$TAG-macos-universal2.dmg" >> $GITHUB_ENV
            echo "PATH_IN_ARCHIVE=mujoco.framework/Versions/A/libmujoco.$TAG.dylib" >> $GITHUB_ENV
            ;;

          linux_arm)
            echo "FINAL_FILE_NAME=libmujoco_arm.so" >> $GITHUB_ENV
            echo "ARCHIVE_FILE_NAME=mujoco-$TAG-linux-aarch64.tar.gz" >> $GITHUB_ENV
            echo "PATH_IN_ARCHIVE=mujoco-$TAG/lib/libmujoco.so.$TAG" >> $GITHUB_ENV
            ;;

          linux_x86)
            echo "FINAL_FILE_NAME=libmujoco_x86.so" >> $GITHUB_ENV
            echo "ARCHIVE_FILE_NAME=mujoco-$TAG-linux-x86_64.tar.gz" >> $GITHUB_ENV
            echo "PATH_IN_ARCHIVE=mujoco-$TAG/lib/libmujoco.so.$TAG" >> $GITHUB_ENV
            ;;
        esac

    - name: Download archive
      uses: valitydev/action-download-file@v1
      with:
        url: https://github.com/google-deepmind/mujoco/releases/download/${{ env.TAG }}/${{ env.ARCHIVE_FILE_NAME }}
        target-path: .

    - name: Setup 7zip
      uses: AnimMouse/setup-p7zip-fork@v1

    - name: Extract library binary
      run: |
        /opt/7z e ${{ env.ARCHIVE_FILE_NAME }} -so ${{ env.PATH_IN_ARCHIVE }} > ${{ env.FINAL_FILE_NAME }}

    - name: Upload to release
      run: |
          gh release upload ${{ env.TAG }} ${{ env.FINAL_FILE_NAME }}
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
