name: 'Upstream Sync'

on:
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: main
    
      - name: Sync master with upstream latest
        uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
        with:
          upstream_repository: google-deepmind/mujoco
          upstream_branch: main
          target_branch: main
          git_fetch_args: --tags
          git_pull_args: --tags
          git_push_args: --tags
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}