name: UPM

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to merge"
        required: true
        type: string
  push:
    tags:
      - '*'
      - '!upm-*'

jobs:
  sync-to-upm:
    runs-on: ubuntu-latest
    environment: OpenUPM workflows
    steps:
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.UPM_TOKEN_APP_ID }}
        private-key: ${{ secrets.UPM_TOKEN_APP_PRIVATE_KEY }}
    - name: Set environment variables
      run: |
        echo "TAG_NAME=${{ inputs.tag_name || env.GITHUB_REF_NAME }}" >> $GITHUB_ENV
        echo "ACCESS_TOKEN=${{ steps.generate-token.outputs.token }}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: upm
    - name: Setup user
      uses: fregante/setup-git-user@v2
    - name: Merge
      run: |
        git merge ${{ env.TAG_NAME }}
        git push
        echo "MERGE_COMMIT_HASH=$(git rev-parse --verify HEAD)" >> $GITHUB_ENV
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ ACCESS_TOKEN }}
      with:
        tag_name: upm-${{ env.TAG_NAME }}
        release_name: UPM - ${{ env.TAG_NAME }}
        commitish: ${{ env.MERGE_COMMIT_HASH }}
