name: UPM

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to merge"
        required: true
        type: string
  push:
    tags:
      - '*'
      - '!upm-*'

env:
  TAG_NAME: ${{ inputs.tag_name || $GITHUB_REF_NAME }}

jobs:
  sync-to-upm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: upm
    - name: Merge
      run: git merge $TAG_NAME
    - name: Create tag
      uses: rickstaa/action-create-tag@v1.7.2
      with:
        tag: upm-$TAG_NAME